version: '3'
services: 
  osticket:
    build: .
    ports:
     - "80:80"
    links:
     - mysql:mysql   
     - memcached:memcached
    environment:
       USE_MEMCACHE: y

  mysql:
    image: mysql:5.7
    restart: always     
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpw
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: mysecretpw

  memcached:
    image: bitnami/memcached:latest
    restart: always
          

 
